Fix #232 requisitar a cada 2 horas
BotGaia/Gaia-Ciclone pull request #2
Opened 2019-06-06 04:30 UTC by LhTaira

Nesse pull request foi feito:

História #26
Issue #232
Requisição para API de duas em duas horas, rota para obtenção de cyclones acontecendo.

2019-06-06 11:00 UTC, CalebeRios requested changes

2019-06-06 11:00 UTC, CalebeRios commented on src/index.js
> +const CycloneTimer = require('./utils/cycloneTimerUtil');
Porque letra maiuscula?

2019-06-06 11:00 UTC, CalebeRios commented on src/models/CycloneModel.js
> +const CycloneModel = mongoose.model('CycloneModel', CycloneSchema);
Porque vocês estão salvando o cyclone? A ideia é que ele requisite e já mande para quem tem a preferência salva. Não faz sentido salvar esses dados se só vamos utilizar ele 1 vez

2019-06-06 11:00 UTC, CalebeRios commented on src/requests/cycloneRequest.js
> +      axios.get('https://api.aerisapi.com/tropicalcyclones/?&filter=all&format=json', { params })
Coloca esse `filter` e o `format` dentro do params também

2019-06-06 11:00 UTC, CalebeRios commented on src/requests/cycloneRequest.js
> +      axios.get('https://api.aerisapi.com/tropicalcyclones/?&filter=all&format=json', { params })
Não precisa do `&` antes do filter. Utilize ele como params para arrumar

2019-06-06 14:29 UTC, LhTaira commented on src/models/CycloneModel.js
> +const CycloneModel = mongoose.model('CycloneModel', CycloneSchema);
Está sendo salva a ultima requisição feita pra API, que e substituída a cada nova requisição.
A ideia era ter a ultima resposta da API salva para mandar para quem fizer requisição ao Gaia-Ciclone pois tinhamos entendido que deveria ser assim.

2019-06-06 23:28 UTC, CalebeRios commented on src/models/CycloneModel.js
> +const CycloneModel = mongoose.model('CycloneModel', CycloneSchema);
Foi conversado durante a daily. Esta tudo correto

2019-06-07 00:18 UTC, AmandaMuniz approved these changes
Ok

2019-06-07 20:30 UTC, CalebeRios approved these changes

2019-06-07 20:30 UTC, merged